# Practicing Gradiant Descent & Ridge Regression

## Loading Iris Data

In [1]:
TRAINING_DATA_PATH = "datasets/houses_train.csv"
TEST_DATA_PATH = "datasets/houses_test.csv"
IRIS_DATA_PATH = "datasets/iris_data.csv"

In [2]:
import pandas as pd

iris_data = pd.read_csv(IRIS_DATA_PATH)
iris_data

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [3]:
training_data = iris_data.sample(frac=0.8)
testing_data = iris_data.drop(index=training_data.index)

## Regression: Predicting Petal Width

The goal here is to predict the performance of a model produces through gradient descent compared to minimising the error directly. This will be done by measureing performance metrics for models produced through both methods on how well they are able to predict petal width given the other variables in the dataset excluding species.

### Prepping the Data

In [4]:
training_data_fatures = training_data[["sepal_length", "sepal_width", "petal_length"]]
training_data_y = training_data["petal_width"]

testing_data_features = testing_data[["sepal_length", "sepal_width", "petal_length"]]
testing_data_y = testing_data["petal_width"]

### Training the Models

In [ ]:
from models.gradient_descent import GDRegresser

gd_regresser = GDRegresser(
    training_data_fatures, training_data_y, 0, 0.00001, 0.000000000007
)
gd_regresser.train()
gd_regresser

In [ ]:
from models.direct_minimisation import DMRegresser

dm_regresser = DMRegresser(training_data_fatures, training_data_y)
dm_regresser.train()
dm_regresser

y = -0.29 + -0.20x1 + 0.23x2 + 0.53x3

### Defining Performance Metrics

#### Mean Squared Error

- Sensitive to outliers
- Changes units

$$
MSE = \frac{1}{n} \sum^n_{i=1}{(y_i-\hat{y}_i)^2}
$$

In [ ]:
def MSE(y_true, y_pred):
    return ((y_true - y_pred) ** 2).mean()

#### Root Mean Squared Error

- sensetive to outliers (inheiriting from quadratic nature of MSE)
- Keeps same units as data 

$$
RMSE = \sqrt{MSE}
$$

In [ ]:
def RMSE(y_true, y_pred):
    return MSE(y_true, y_pred) ** 0.5

#### Mean Absolute Error

- cannot be used for optimisation due to absolute function
- keeps real world units
- resistant to outliers (linear function)

$$
\frac{1}{n} \sum^n_{i=1}{|y_i-\hat{y}_i|}
$$

In [ ]:
def MAE(y_true, y_pred):
    return (y_true - y_pred).abs().sum() / len(y_true)

### Testing the Models

In [ ]:
from pandas import DataFrame, Series


def model_test_results(predictions):
    return Series(
        {
            "MSE": MSE(testing_data_y, predictions),
            "RMSE": RMSE(testing_data_y, predictions),
            "MAE": MAE(testing_data_y, predictions),
        }
    )

In [ ]:
DataFrame(
    [
        model_test_results(gd_regresser.predict(testing_data_features)),
        model_test_results(dm_regresser.predict(testing_data_features)),
    ],
    index=["Gradient Descent", "Direct Method"],
)

                       MSE      RMSE       MAE
Gradient Descent  0.021976  0.148242  0.121754
Direct Method     0.021976  0.148242  0.121754

The difference is between the two approaches of training is unarguably neglagable, however the direct minimisation approach took significantly less time. This can be attributed to the small number of features, meaning only a 3x3 matrix needed to be inverted.

## Classification: Classifying Iris Type

In [ ]:
training_features = training_data.drop(columns=["species"])
training_labels = training_data["species"]

testing_features = testing_data.drop(columns=["species"])
testing_labels = testing_data["species"]

In [ ]:
from models.gradient_descent import SGDClassifier

gd_classifier = SGDClassifier(
    training_features,
    training_labels == "Iris-setosa",
    0.01,
    0.00001,
    0,  # stop only when perfect score reached (risk overfitting)
)


gd_classifier.train()

gd_classifier.classify(testing_features) == (testing_labels == "Iris-setosa")

5      True
7      True
8      True
13     True
14     True
40     True
49     True
52     True
56     True
57     True
58     True
68     True
76     True
78     True
84     True
88     True
91     True
94     True
99     True
100    True
101    True
108    True
110    True
118    True
121    True
125    True
128    True
133    True
137    True
146    True
dtype: bool